# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Yueyi Liao
title: Where Psychology Meets Hospitality
email: liaoyueyi@gmail.com
# email_title: Email (Email title override)
phone: "+1 (424) 393-6876"
# phone_title: Phone (Phone title override)
website: yueyiliao.github.io
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: yueyi_ueue
linkedin_username: yueyi-liao
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/Avatar.jpg
about_content: |-
  **_Introduction_**
  - I am a senior at the **University of California, Riverside**, majoring in **Psychology**, and an applicant for the **Global Hospitality** and **Culinary Arts programs** at **New York University** and the **Culinary Institute of America**.
  - As an aspiring culinary and hospitality professional, my goal is to combine my understanding of human behavior with my passion for food and service to create genuine, luxurious, and memorable banquet experiences.

  **_Experience and Growth_**
  - Hosted cultural and themed dinners for international students far from home, volunteered in community hospitality services, and organized pastry-making events supporting the local autism community.
  - Through these experiences, I have gained hands-on skills in food preparation, event coordination, and teamwork — and learned how hospitality brings people together through warmth, care, and thoughtful attention to detail.

  **_Work Ethic and Values_**
  - Reliable, calm under pressure, and attentive to every detail — whether serving guests, collaborating with a team, or preparing a dish.
  - Remain professional and composed in fast-paced environments, always striving to deliver comfort and care through genuine service.

  **_Professional Training_**
  - ServSafe Food Protection Manager, California Food Handling, and Responsible Beverage Service.
  - SHRM Essentials of Human Resources — teamwork, organizational communication, inclusive leadership.
  - Currently pursuing advanced training and preparing for an **internship (April–August 2026)** to gain practical experience in **hospitality operations** (event & banquet) and **kitchen management** (restaurants & bars).

  **_Career Vision_**
  - My long-term goal is to continue growing in the hospitality industry, developing my craft through lifelong learning, teamwork, and dedication to excellent service.
  - I aspire to create meaningful hospitality experiences that **celebrate culture**, **value sustainability**, **respect community**, and **foster human connection**.

content:
  - title: "CULINARY & COMMUNITY PROJECTS"
    layout: list
    content:
      - layout: left
        border: weak
        title: Lunar New Year Feast Series
        quote: >
          Annual cultural dining experience celebrating tradition, creativity, and community.
        description: |
          Hosted and prepared multi-course Lunar New Year feasts for 10–20 guests each year.
          Managed sourcing, menu design, timing, and presentation to ensure a smooth, satisfying dining experience.
          Learned how to tell cultural stories through food, atmosphere, and hospitality.

      - layout: left
        border: weak
        title: Community Baking Event — “Friends” Autism Support Program
        quote: >
          Baking workshops connecting children with autism and their caregivers — plus guest talks promoting awareness and inclusion.
        description: |
          Co-organized hands-on pastry sessions where children and caregivers decorated cakes together, creating shared moments of connection and pride.
          Coordinated logistics, preparation, and safety; invited guest speakers to raise inclusion awareness.
          Learned to use hospitality as a bridge for empathy and community engagement.

      - layout: left
        border: weak
        title: Recipe Development & Sharing — “Xia Chu Fang” Platform
        quote: >
          Original recipes blending home-style techniques with creative flavor pairing and presentation.
        description: |
          Developed, tested, and published original recipes on Xia Chu Fang, meaning "to cook", an online cooking platform.
          Focused on clear instructions, plating, and food photography to improve accessibility and appeal.
          Iterated based on community feedback to refine flavor balance and timing.

  - title: "KNOWLEDGE & RESEARCH"
    layout: list
    content:
      - layout: left
        border: weak
        title: Research Proposal — Investment Model and Commitment in Long-Distance vs. Proximal Relationships
        caption: May 2025
        quote: >
          Exploring how relationship experiences and future planning shape emotional commitment across distances.
        description: |
          Developed a research proposal expanding Rusbult’s Investment Model to examine how past experiences and future planning predict commitment in long-distance and proximal relationships.
          Designed survey methodology for 500 participants and proposed ANOVA analysis to compare commitment mechanisms.
          Applied behavioral science concepts to understand long-term engagement and emotional investment.

      - layout: left
        border: weak
        title: Research Proposal — Gender-Bias Awareness Intervention in Childhood Development
        caption: January 2025
        quote: >
          Designing a longitudinal study to examine how parental awareness programs influence children’s confidence and identity.
        description: |
          Created a study exploring how increasing parental awareness of gender bias affects children’s self-concept and behavior.
          Integrated Implicit Association Tests (IAT) and survey methods to evaluate shifts in parental bias and child development.

      - layout: left
        border: weak
        title: Research Presentation — PTSD Symptoms and Sleep Disturbances
        caption: June 2024
        quote: >
          Presentation of Dietch et al. (2019) on PTSD symptoms and sleep in World Trade Center responders.
        description: |
          Collaborated with a team to synthesize and present the paper’s methodology and findings for a class audience.
          Focused on clear communication of study design, variables, and real-world implications for occupational health.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Behavior Frontiers
        sub_title: Behavior Technician
        caption: October 2025 – Present
        link: https://www.behaviorfrontiers.com
        quote: >
          Providing individualized behavioral support for clients with developmental needs.
        description: |
          Apply empathy and observational skills to support clients with developmental and behavioral challenges.
          Collaborate with supervisors and families to implement individualized support plans.
          Strengthen communication, patience, and situational awareness — directly transferable to hospitality and guest experience management.

      - layout: right
        title: Zhengzhou No.1 People’s Hospital
        sub_title: Medical Intern
        caption: July – August 2021
        quote: >
          Assisted physicians and staff in a fast-paced hospital environment.
        description: |
          Supported patient communication and administrative coordination while observing clinical procedures.
          Maintained accurate records and assisted with daily operations.
          Developed adaptability, professionalism, and attention to detail.

      - layout: right
        title: Harvest Pack Meal Packing Event
        sub_title: Community Volunteer
        caption: Planned for November 2025
        link: https://www.harvestpack.org
        quote: >
          Collaborative community event to assemble meals for families in need.
        description: |
          Will collaborate with 200+ volunteers to assemble 100,000 meal packs for families in Central America.
          Expect to strengthen teamwork, time management, and community engagement in a mission-driven environment.

      - layout: right
        title: Private Family Employment
        sub_title: Babysitter
        caption: 2023 – Present
        quote: >
          Providing daily care and support for two children.
        description: |
          Prepare balanced meals and assist with homework while ensuring a safe and supportive environment.
          Communicate regularly with parents to maintain trust and consistency.

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of California, Riverside
        sub_title: Bachelor of Arts in Psychology
        caption: September 2022 – June 2026 (expected)
        quote: >
          Coursework emphasizing human behavior, communication, and social psychology — connecting insight with service and hospitality.
        description: |
          Relevant coursework includes Social Psychology, Cognitive Psychology, Industrial–Organizational Psychology, and Research Methods.

      - layout: top-right
        title: Culinary Institute of America
        sub_title: Accelerated Culinary Arts Certificate Program (Application in Progress)
        caption: Planned 2026 Enrollment
        quote: >
          Advanced professional training in culinary arts and kitchen management.
        description: |
          Preparing an application to gain hands-on culinary experience and technical mastery in fine dining, event operations, and hospitality service excellence.

      - layout: top-right
        title: New York University
        sub_title: Global Hospitality Management Program (Application in Progress)
        caption: Planned 2026 Enrollment
        quote: >
          Specialized program integrating global service leadership and hospitality innovation.
        description: |
          Applying to deepen understanding of international service design, luxury guest experience, and sustainable business practices.

          
  - title: A Little More About Me
    layout: text
    content: |
      I’m drawn to spaces where people gather — the quiet moments before an event begins, the aroma that fills a room, the way light softens as conversation grows. I notice how details shape comfort, how a simple gesture can turn service into care.
      In those moments, I’m reminded why I love hospitality: it’s where thoughtfulness becomes experience.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
