# Site
repository: yueyiliao/yueyiliao.github.io

version: 2

# Personal info
name: Yueyi Liao
title: Bachelor Degree of Art, Psychology | Aspiring Hospitality & Culinary Professional
email: yueyiliao@gmail.com
phone: 424-393-6876
website: https://yueyiliao.github.io

darkmode: false

# Social links
linkedin_username: www.linkedin.com/in/yueyi-liao
instagram_username: yueyi_ueue
github_username: yueyiliao

# About Section
about_profile_image: images/profile.jpg
about_content: |
  Hello! I’m **Yueyi Liao**, a Psychology student at the University of California, Riverside, 
  with a growing passion for **hospitality management and culinary arts**.  

  My background in psychology has taught me to understand people, emotions, and teamwork — skills 
  that beautifully translate into creating meaningful dining and guest experiences.  

  I’ve contributed to **event coordination, volunteer service, and culinary projects**, and 
  I’m eager to continue learning in environments that combine creativity, care, and culture.  

content:
  - title: Past Experiences
    layout: list
    content:
      - layout: left
        title: CAVA Restaurant
        sub_title: Frontline Team Member
        caption: 2024 – Present
        quote: >
          Fast-casual Mediterranean restaurant known for fresh ingredients and vibrant hospitality.
        description: |
          • Delivered welcoming and efficient customer service during high-volume hours.  
          • Collaborated closely with the team to maintain consistency and speed.  
          • Developed strong communication, multitasking, and guest-relations skills.  

      - layout: left
        title: Event Volunteer | UCR International Student Office
        sub_title: Cultural Event Support
        caption: 2023 – Present
        quote: >
          Supported multicultural campus events connecting students through shared experiences.  
        description: |
          • Assisted in organizing and setting up events like Lunar New Year celebrations.  
          • Greeted attendees and managed registration tables.  
          • Coordinated with staff to ensure smooth event flow.  

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: University of California, Riverside
        sub_title: B.A. in Psychology
        caption: Expected Graduation: 2026
        quote: >
          Coursework in social psychology, communication, and human behavior.
        description: |
          • Gaining insight into interpersonal dynamics and teamwork.  
          • Exploring how psychology applies to service, experience design, and hospitality.

  - title: Career Goals & Plans
    layout: text
    content: |
      I aim to combine my studies in psychology with hands-on hospitality experience to create 
      meaningful, people-centered dining and service environments.  

      My short-term goal is to gain an internship or trainee position in the **hospitality or 
      restaurant management industry**, learning from professionals who value both craft and care.  
      In the long term, I hope to continue my education at the **Culinary Institute of America (CIA)** 
      to refine my culinary skills and leadership abilities.

  - title: Culinary Creations
    layout: list
    content:
      - layout: left
        title: Homemade Projects
        sub_title: Recipe Development & Experimentation
        caption: Ongoing
        description: |
          • Experimented with dishes inspired by Chinese and Western cuisines.  
          • Styled and photographed meals for social media.  
          • Shared food with friends and community, emphasizing presentation and balance.

  - title: Skills & Interests
    layout: text
    content: |
      **Skills**
      - Customer service & teamwork  
      - Event coordination  
      - Cross-cultural communication  
      - Food presentation & plating  
      - Time management

      **Interests**
      - Culinary art & baking  
      - Food culture and travel  
      - Psychology of dining experiences  
      - Aesthetics & photography  

footer_show_references: true
references_title: References available upon request

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]

